### ISSUE TITLE
add WSS support

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-android#8]

**Comment by prasad-1210** [comment]
+1 for wss support from autobahn. I've been watching this space since last 1 year for WSS ):

**Comment by xsren** [comment]
+1 for wss support from autobahn.

**Comment by ilber** [comment]
+1 for wss support from autobahn.

**Comment by LoveWalter** [comment]
+1 for wss support from autobahn..

**Comment by zeuscode** [comment]
+1 for wss support from autobahn..

**Comment by rsclmumbai** [comment]
+1 for wss support from autobahn.

**Comment by rsclmumbai** [comment]
BTW, is there any work around to have a secure data exchange?

**Comment by szczepaan** [comment]
is this alive ?

**Comment by goeddea** [comment]
We have found somebody who will do an update of Autobahn|Android (which will include support for WAMP v2). No definite timeline yet (best guess at the moment: Q3).

**Comment by oberstet** [comment]
this will be addressed as part of https://github.com/crossbario/autobahn-android/issues/92

**Comment by szczepaan** [comment]
Any status  update on that timeline?

**Comment by RabbitPie** [comment]
+1 for wss support from autobahn.

**Comment by atonamy** [comment]
Hey today November 2016 and still no any official support for wss :( 
I like this library but it's useless for production because ssl is very important for commercial app.
We tried to use this implementation https://github.com/palmerc/SecureWebSockets but is memory leak issue in the code :(

There only one stable option for Android now so far is https://github.com/TooTallNate/Java-WebSocket which is support ssl. The rest solutions is useless because lack of full wss support for websockets.

Why like this? Why we don't have strong secure layer support in websocket libraries for Android? Websocket is not popular for professional developers? Or anyone don't care about sensitivity of their data in apps and use ws in production?

**Comment by erobic** [comment]
@atonamy Neovisionaries web socket client: https://github.com/TakahikoKawasaki/nv-websocket-client also supports wss.

**Comment by atonamy** [comment]
@erobic
Thanks a lot for reference.
