### ISSUE TITLE
Autobahn won't build against Android-23

### ISSUE THREAD

**Issue by mhess-connectify** [crossbario/autobahn-android#85]
Hi,

Autobahn uses the deprecated http client packge org.apache.http, which has been removed in Android-23.  Is there any plan to migrate Autobahn to use URLConnection, or something else? Will tavendo accept a patch to implement this?

More information here:
http://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

**Comment by goeddea** [comment]
Unfortunately we currently don't have the resources to work on AutobahnAndroid. We would appreciate any contributions that bring the project forward.

**Comment by arashmidos** [comment]
Add `org.apache.http.legacy.jar` to your lib folder and it will temporarily solve your problem. You may find it in `...\sdk\platforms\android-23\optional` folder.

Our project is heavily depends on AutobahnAndroid which has some crashes due to use of "apache http" library. Is there another library to replace by autobahn?

**Comment by oberstet** [comment]
after long pause, we'll take up development again https://github.com/crossbario/autobahn-android/issues/92

minimum supported android version will be 4.1+
