### ISSUE TITLE
Proposing jawampa library

### ISSUE THREAD

**Issue by firasalkafri** [crossbario/autobahn-android#94]
We are using [Jawampa](https://github.com/Matthias247/jawampa) library in some of our products and we would like to propose using it to release the next version of Autbahn Android with support to WAMPv2.

I would like to hear your thoughts and ideas and if a move like this is going to be acceptable by the project's maintainers.

**Comment by oberstet** [comment]
No, we won't use jawampa. But it seems to be possible: https://github.com/jrogers/AndroidWampExample

**Comment by firasalkafri** [comment]
@oberstet any updates on the next Android version release date?

**Comment by oberstet** [comment]
@firasalkafri we are talking to a contract developer and we (Tavendo / Crossbar.io) will sponsor work on WAMPv2 and WSS and more .. pls see : https://github.com/crossbario/autobahn-android/issues/92

**Comment by firasalkafri** [comment]
@oberstet that's great to hear after all that wait, I am honestly trying to push and initiate developing a good WAMP2 library for Android built using some of Jawampa's code. I would love to hear your thoughts one why you're not planning to use if for next release.

**Comment by oberstet** [comment]
@firasalkafri In general, I subscribe to the "reuse instead of reinvent the wheel" idea. And jawampa is certainly a good fellow in the WAMP ecosystem (and an important one when considering the server side).

In this case, there are 2 aspects that make that less attractive:

1. Android has a couple of specifics that need to be addressed for full/proper Android support (eg you can't have any networking on the main thread)
2. as this project is one of the Autobahn family, we (Tavendo / Crossbar.io), it must pass our QS standards, internal intergration testing (vs Crossbar.io) and we will provide commercial support in the future for it - and we cannot do that when we don't have the internal know-how / control over this thing

I hope this makes some sense ..

**Comment by firasalkafri** [comment]
Got you, thanks!

Best,

Firas K.
Mobile : +962785121960
Google+ - Linkedin - Twitter - Facebook

On April 10, 2016 at 5:53:29 PM, Tobias Oberstein (notifications@github.com) wrote:

@firasalkafri In general, I subscribe to the "reuse instead of reinvent the wheel" idea. And jawampa is certainly a good fellow in the WAMP ecosystem (and an important one when considering the server side).

In this case, there are 2 aspects that make that less attractive:

Android has a couple of specifics that need to be addressed for full/proper Android support (eg you can't have any networking on the main thread)
as this project is one of the Autobahn family, we (Tavendo / Crossbar.io), it must pass our QS standards, internal intergration testing (vs Crossbar.io) and we will provide commercial support in the future for it - and we cannot do that when we don't have the internal know-how / control over this thing
I hope this makes some sense ..
